### ISSUE TITLE
[bug] The shortcut keys often fail, and the plugin needs to be restarted frequently

### ISSUE THREAD

**Issue by wenbopeng** [michaellee/soomda#1]

**Comment by michaellee** [comment]
Hi! Can you share more details? Soomda, doesn't ship with any shortcut keys so I'm unsure what you're referring to. Thanks!

**Comment by wenbopeng** [comment]
![image](https://user-images.githubusercontent.com/74350447/233236928-4a1e8263-8f8b-4049-b3de-81bbfdfc2ff4.png)
![image](https://user-images.githubusercontent.com/74350447/233237294-429fcc23-ef57-41f6-bf1f-e2155ea3e763.png)

**Comment by michaellee** [comment]
Hey @wenbopeng I just pushed up an updated for 1.0.4 where this bug should be resolved. Do you mind updating your version and letting me know if that fixed it for you as well? Thanks!

**Comment by wenbopeng** [comment]
> Hey @wenbopeng I just pushed up an updated for 1.0.4 where this bug should be resolved. Do you mind updating your version and letting me know if that fixed it for you as well? Thanks!

Yes, it solved after update, awsome!
