### ISSUE TITLE
Plugin ID mismatch

### ISSUE THREAD

**Issue by joethei** [michaellee/soomda#2]
Hi @michaellee,

We noticed that you changed the ID of your plugin in your manifest a while ago.
This means that your plugin is no longer installable from the community plugin list inside Obsidian.
We would recommend changing it back to `obsidian-soomda`, to make it installable again, and not cause issues for existing users.

- the Obsidian Team

**Comment by michaellee** [comment]
Thanks @joethei for pointing this out. I've patched this in https://github.com/michaellee/soomda/releases/tag/1.0.3

For this reason, closing this issue out. Thanks again for bringing this to my attention!
